"""Projection-oriented dashboard for the transparent hybrid demonstration."""

HYBRID_DASHBOARD_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Compute Echo — Hybrid Demonstration</title>
<style>
:root{--bg:#070b13;--panel:#0d1422;--line:#233149;--text:#f5f7fb;--muted:#95a3b8;--blue:#4299ff;--purple:#a879ff;--orange:#ff9d42;--green:#42d69b;--red:#ff5c68;--gray:#6f7d91;--amber:#f2c14e}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -10%,#17233b 0,var(--bg) 44%);color:var(--text);font:15px Inter,Segoe UI,system-ui,sans-serif;min-height:100vh}button,select{font:inherit}
.shell{max-width:1500px;margin:auto;padding:18px 28px 24px}.top{display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-size:30px;font-weight:800;letter-spacing:-.7px}.brand span{color:var(--blue)}
.disclosure{border:1px solid var(--amber);background:#2a230d;color:#ffe394;padding:9px 16px;border-radius:4px;font-weight:800;letter-spacing:.7px}.replay{display:none;background:#342509;border:2px solid var(--amber);padding:10px;text-align:center;font-size:17px;font-weight:900;margin-top:12px}.replay.on{display:block}
.stage{display:grid;grid-template-columns:1fr .8fr 1fr;gap:14px;align-items:stretch;margin-top:16px}.node,.routebox,.panel,.finding{background:linear-gradient(180deg,#111a2a,#0b111d);border:1px solid var(--line);border-radius:10px;padding:15px;box-shadow:0 12px 35px #0005}.node h2{margin:2px 0 6px;font-size:19px}.eyebrow{font-size:11px;color:var(--muted);font-weight:800;letter-spacing:1.4px}.hardware{font-size:22px;font-weight:800}.region{color:var(--muted);margin-top:4px}.connection{display:inline-flex;align-items:center;gap:7px;margin-top:13px;color:var(--amber);font-size:13px}.connection::before{content:'';width:9px;height:9px;border-radius:50%;background:var(--amber);box-shadow:0 0 10px var(--amber)}.connection.on{color:var(--green)}.connection.on::before{background:var(--green);box-shadow:0 0 10px var(--green)}
.routebox{text-align:center;display:flex;flex-direction:column;justify-content:center}.route-name{font-size:13px;color:var(--muted)}.route-line{height:4px;background:#26344b;margin:24px 10px;position:relative}.route-line:before,.route-line:after{content:'';position:absolute;top:50%;width:12px;height:12px;border-radius:50%;background:var(--gray);transform:translateY(-50%)}.route-line:before{left:-2px}.route-line:after{right:-2px}.route-line.active{background:var(--blue);box-shadow:0 0 15px var(--blue)}.route-line.forwarded{background:var(--orange);box-shadow:0 0 15px var(--orange)}.packet{position:absolute;top:50%;left:4%;width:15px;height:15px;border-radius:2px;background:white;transform:translateY(-50%) rotate(45deg);display:none}.route-line.active .packet{display:block;animation:packet 1.6s linear infinite}.route-line.local .packet{animation:localpulse 1.2s ease-in-out infinite}@keyframes packet{to{left:94%}}@keyframes localpulse{50%{transform:translateY(-50%) rotate(45deg) scale(1.7);opacity:.35}}
.modebadge{font-size:22px;font-weight:900}.modebadge.local{color:var(--blue)}.modebadge.forwarded{color:var(--orange)}
.panel{margin-top:14px}.panel-head{display:flex;justify-content:space-between;align-items:end;gap:15px}.panel h3{margin:0;font-size:16px}.source-label{font-size:11px;color:#ffd979;letter-spacing:.7px;font-weight:800}.barcode{display:flex;height:42px;margin-top:12px;border-radius:6px;overflow:hidden;position:relative;background:#111827}.bar{display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:900;border-right:2px solid #07101c}.bar.TENSOR{background:var(--blue)}.bar.MEMORY{background:var(--purple)}.bar.MIXED{background:var(--orange);color:#151515}.bar.IDLE{background:var(--gray)}.playhead{position:absolute;left:0;top:0;bottom:0;width:3px;background:white;box-shadow:0 0 13px white;z-index:5;transition:left .2s linear}
.charts{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:10px}.chart-card{border:1px solid #1e2b40;background:#080e18;border-radius:7px;padding:10px}.chart-title{display:flex;justify-content:space-between;font-size:12px;margin-bottom:5px}.legend span{margin-left:12px}.p{color:var(--orange)}.c{color:var(--blue)}.m{color:var(--purple)}canvas{display:block;width:100%;height:200px}.ground{color:#d7c6ff}.raw-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.raw-grid canvas{height:150px}.diagnostic{color:#aeb9ca;font-size:12px}
.findings{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:14px}.finding{min-height:112px}.finding .label{font-size:11px;color:var(--muted);letter-spacing:1.2px;font-weight:800}.finding .value{font-size:24px;font-weight:900;margin-top:16px}.good{color:var(--green)}.pending{color:var(--amber)}.contradiction{border-color:var(--red);box-shadow:0 0 28px #ff5c6825}.contradiction .value{color:var(--red)}
.headline{text-align:center;font-size:29px;font-weight:950;letter-spacing:.2px;min-height:44px;margin:15px 0 4px}.headline.bad{color:var(--red)}.controls{display:flex;align-items:center;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:12px}.controls button,.controls select{border:1px solid #33445f;background:#121d30;color:white;border-radius:5px;padding:10px 15px;font-weight:800;cursor:pointer}.controls button:hover{border-color:var(--blue)}.controls .primary{background:#164d80;border-color:var(--blue)}.controls .forward{background:#5b3515;border-color:var(--orange)}.controls .auto{background:#174b39;border-color:var(--green)}.controls button:disabled{opacity:.45;cursor:not-allowed}
.error{display:none;border:1px solid var(--amber);background:#2a210d;color:#ffe394;padding:10px;margin-top:12px}.error.on{display:block}.facts{font-size:13px;color:var(--muted);margin-top:9px}.facts b{color:white}details{margin-top:12px;border-top:1px solid var(--line);padding-top:10px;color:var(--muted)}summary{cursor:pointer;color:#cdd6e4;font-weight:700}pre{white-space:pre-wrap;max-height:260px;overflow:auto;font-size:11px;background:#050911;padding:10px}.footer{text-align:center;color:#66758c;font-size:11px;margin-top:12px}
@media(max-width:900px){.stage,.charts,.findings{grid-template-columns:1fr}.routebox{min-height:130px}.shell{padding:14px}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="shell">
<div class="top"><div><div class="eyebrow">STRATEGIC COMPUTE VERIFICATION</div><div class="brand">Compute <span>Echo</span></div></div><div class="disclosure">LIVE COMPUTE + SIMULATED FACILITY METERS</div></div>
<div id="replayBanner" class="replay">REPLAY OF PREVIOUSLY CAPTURED DEMONSTRATION</div>
<section class="stage">
 <article class="node"><div class="eyebrow">DECLARED SITE</div><h2>US Northeast Facility</h2><div id="facilityModel" class="hardware">NVIDIA H100 80GB HBM3</div><div id="facilityRegion" class="region">US Northeast</div><div class="source-label">LIVE AUTHENTICATED WORKER</div><div id="facilityConnection" class="connection">Checking facility</div><div class="facts">Fresh challenges · <b>digest verified</b></div></article>
 <article class="routebox"><div class="route-name">ACTUAL AUTHENTICATED WORKER ROUTE</div><div id="routeLine" class="route-line"><i class="packet"></i></div><div id="routeMode" class="modebadge">ROUTE UNCONFIRMED</div><div id="routeFact" class="facts">Stage ground truth, never detector evidence</div></article>
 <article class="node"><div class="eyebrow">REMOTE HELPER · PRIVATE DEMO GROUND TRUTH</div><h2>Iceland Helper</h2><div id="helperModel" class="hardware">NVIDIA H100 80GB HBM3</div><div id="helperRegion" class="region">Iceland / Europe</div><div class="source-label">LIVE AUTHENTICATED WORKER</div><div id="helperConnection" class="connection">Checking helper</div><div id="helperLiveFact" class="facts">Waiting for a forwarded response</div></article>
</section>
<section class="panel"><div class="panel-head"><div><h3>Unpredictable time-coded challenge</h3><div id="pattern" class="facts">Pattern echo-demo-001</div></div><div id="progress" class="facts">Ready</div></div><div id="barcode" class="barcode"><div class="playhead" id="playhead"></div></div>
 <div class="charts">
  <div class="chart-card"><div class="chart-title"><b>Simulated US facility response</b><span class="source-label">DECLARED FACILITY METER DIGITAL TWIN — SIMULATED</span></div><canvas id="facilityChart" width="720" height="220"></canvas><div class="legend"><span class="p">● Power</span><span class="c">● Compute</span><span class="m">● Memory</span></div></div>
  <div class="chart-card"><div class="chart-title"><b>Simulated Iceland facility response</b><span class="source-label ground">REMOTE FACILITY METER DIGITAL TWIN — SIMULATED DEMO GROUND TRUTH</span></div><canvas id="helperChart" width="720" height="220"></canvas><div class="legend"><span class="p">● Power</span><span class="c">● Compute</span><span class="m">● Memory</span></div></div>
 </div>
</section>
<section class="findings"><article class="finding"><div class="label">MATHEMATICAL CORRECTNESS</div><div id="mathResult" class="value pending">PENDING</div><div id="freshFact" class="facts">Waiting for a fresh challenge</div></article><article class="finding"><div class="label">PERFORMANCE / DEADLINE</div><div id="deadlineResult" class="value pending">PENDING</div><div id="timingFact" class="facts">End-to-end timing not started</div></article><article id="physicalCard" class="finding"><div class="label">PHYSICAL-SITE CONSISTENCY · DIGITAL TWIN</div><div id="physicalResult" class="value pending">PENDING</div><div class="facts">Illustrates an independent-meter decision</div></article></section>
<div id="headline" class="headline">READY FOR LIVE HYBRID DEMONSTRATION</div><div id="error" class="error"></div>
<div class="controls"><button onclick="setRoute('local')">RUN LOCALLY</button><button class="forward" onclick="setRoute('forwarded')">FORWARD TO REMOTE HELPER</button><button class="primary" onclick="startScene()">START CHALLENGE</button><button class="auto" onclick="autoDemo()">AUTO DEMO</button><button onclick="resetDemo()">RESET DEMO</button><select id="runMode" onchange="setMode(this.value)"><option value="LIVE_HYBRID">LIVE HYBRID</option><option value="CAPTURE">CAPTURE</option><option value="REPLAY">REPLAY</option></select><button onclick="newPattern()">NEW PATTERN</button></div>
<details><summary>RAW HOST TELEMETRY · technical panel</summary><p class="source-label">LIVE NVML HOST TELEMETRY — DIAGNOSTIC ONLY</p><p class="diagnostic">Direct, unamplified host readings on fixed 0–700 W and 0–100% axes. These short workloads may look nearly flat. This telemetry is neither an independent facility meter nor detector evidence.</p><div class="raw-grid"><div class="chart-card"><b>Declared worker NVML</b><canvas id="rawFacilityChart" width="700" height="160"></canvas></div><div class="chart-card"><b>Helper worker NVML · private demo ground truth</b><canvas id="rawHelperChart" width="700" height="160"></canvas></div></div><p>Challenge seeds are fresh. Expected digests are computed on the laptop before issuance and are not taken from either worker. Completion time is measured by the laptop. Route labels are maintained as stage ground truth and never passed to the digital-twin detector. Both prominent facility signals are generated from a seeded illustrative model with lag, smoothing and bounded noise. No production receipt API exists in HYBRID_DEMO.</p><p><input id="fixedPattern" value="echo-demo-001" maxlength="64"><button onclick="setPattern()">SET REHEARSAL PATTERN</button></p><pre id="details">Waiting for state…</pre></details>
<div class="footer">HYBRID_DEMO · Production physical verification disabled · No simulated value is represented as measured</div>
</main><script>
let lastState=null,pollTimer=null;const q=id=>document.getElementById(id);async function api(path,method='GET'){let r=await fetch(path,{method,headers:{'Content-Type':'application/json'}});if(!r.ok)throw Error(await r.text());return r.json()}
function latest(rows){for(let i=rows.length-1;i>=0;i--){let s=rows[i].sample;if(s&&s.available)return s}return null}
function connection(id,on,label){let e=q(id);e.className='connection'+(on?' on':'');e.textContent=on?label:'Unavailable'}
function barcode(scene){let box=q('barcode');box.querySelectorAll('.bar').forEach(x=>x.remove());let seq=scene&&scene.schedule||[];seq.forEach((mode,i)=>{let b=document.createElement('div');b.className='bar '+mode;b.style.width=(100/seq.length)+'%';b.textContent=mode;box.insertBefore(b,q('playhead'))});if(!seq.length){let b=document.createElement('div');b.className='bar IDLE';b.style.width='100%';b.textContent='AWAITING CHALLENGE';box.insertBefore(b,q('playhead'))}}
function line(ctx,values,color,height,scale){if(values.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{let x=i/(values.length-1)*ctx.canvas.width,y=height-8-Math.max(0,Math.min(1,v/scale))*(height-16);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function drawTwin(id,a){let c=q(id),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#1e2b40';for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,i*c.height/4);x.lineTo(c.width,i*c.height/4);x.stroke()}a=a||[];line(x,a.map(v=>v.facility_power_w),'#ff9d42',c.height,700);line(x,a.map(v=>v.gpu_compute_utilization_pct),'#4299ff',c.height,100);line(x,a.map(v=>v.gpu_memory_utilization_pct),'#a879ff',c.height,100)}
function drawRaw(id,rows){let c=q(id),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);let a=rows.filter(v=>v.sample&&v.sample.available).slice(-160).map(v=>v.sample);line(x,a.map(v=>v.board_or_module_power_draw_w),'#ff9d42',c.height,700);line(x,a.map(v=>v.gpu_compute_utilization_pct),'#4299ff',c.height,100);line(x,a.map(v=>v.gpu_memory_utilization_pct),'#a879ff',c.height,100)}
function render(s){lastState=s;let replay=s.run_mode==='REPLAY';q('replayBanner').className='replay'+(replay?' on':'');q('runMode').value=s.run_mode.replace(' ','_');connection('facilityConnection',s.connections.facility,'LIVE FACILITY CONNECTED');connection('helperConnection',s.connections.helper,'LIVE HELPER CONNECTED');let fs=latest(s.telemetry.declared_site),hs=latest(s.telemetry.remote_helper);if(fs)q('facilityModel').textContent=fs.gpu_model;if(hs)q('helperModel').textContent=hs.gpu_model;q('facilityRegion').textContent=s.facility.region;q('helperRegion').textContent=s.helper.region;
 let route=s.selected_route;q('routeMode').textContent=route==='forwarded'?'FORWARDED US → ICELAND':route==='local'?'EXECUTED LOCALLY':'ROUTE UNCONFIRMED';q('routeMode').className='modebadge '+route;q('routeLine').className='route-line active '+route;q('pattern').textContent='Pattern '+s.pattern_seed;let scene=s.current_scene||s.last_scene;barcode(scene);drawTwin('facilityChart',scene&&scene.declared_facility_digital_twin);drawTwin('helperChart',scene&&scene.remote_facility_digital_twin);let totalDuration=scene&&scene.total_duration_s||1;q('playhead').style.left=Math.min(100,s.scene_elapsed_s/totalDuration*100)+'%';drawRaw('rawFacilityChart',s.telemetry.declared_site);drawRaw('rawHelperChart',s.telemetry.remote_helper);
 let comps=scene&&scene.computations||[],done=comps.filter(v=>v.status==='VERIFIED').length,total=scene&&scene.schedule&&scene.schedule.length||0;q('progress').textContent=s.status+(total?' · '+done+'/'+total+' verified':'');q('freshFact').textContent=comps.some(v=>v.fresh_challenge_issued)?'Fresh challenge issued · answer digest checked':'Waiting for a fresh challenge';let maxTime=Math.max(0,...comps.map(v=>v.end_to_end_s||0));q('timingFact').textContent=maxTime?('Slowest live round trip '+maxTime.toFixed(3)+' s'):'End-to-end timing not started';let helperResponses=comps.filter(v=>v.helper_response_received).length;q('helperLiveFact').innerHTML=helperResponses?('<b>'+helperResponses+' live helper responses</b> returned through facility'):'Waiting for a forwarded response';q('routeFact').textContent=route==='forwarded'&&helperResponses?'Drain complete · authenticated route + helper responses confirmed':'Stage ground truth, never detector evidence';
 let complete=scene&&(s.status==='COMPLETE'||s.status==='REPLAY_COMPLETE');q('mathResult').textContent=complete?scene.computational_status:'PENDING';q('mathResult').className='value '+(complete&&scene.computational_status==='VERIFIED'?'good':'pending');q('deadlineResult').textContent=complete?scene.performance_status:'PENDING';q('deadlineResult').className='value '+(complete&&scene.performance_status.includes('COMPLETED')?'good':'pending');let phy=complete&&scene.digital_twin_result&&scene.digital_twin_result.physical_digital_twin_status||'PENDING';q('physicalResult').textContent=phy;q('physicalResult').className='value '+(phy==='ECHO MATCHED'?'good':phy==='ECHO MISSING'?'':'pending');q('physicalCard').className='finding'+(phy==='ECHO MISSING'?' contradiction':'');let head=complete?scene.headline:(s.status==='RUNNING'?'LIVE CHALLENGE IN PROGRESS':'READY FOR LIVE HYBRID DEMONSTRATION');q('headline').textContent=head;q('headline').className='headline'+(head==='CORRECT ANSWERS — WRONG PHYSICAL SITE'?' bad':'');q('error').className='error'+(s.error?' on':'');q('error').textContent=s.error||'';q('details').textContent=JSON.stringify(s,null,2)}
async function refresh(){try{render(await api('/api/state'))}catch(e){q('error').className='error on';q('error').textContent='Controller unavailable: '+e.message}clearTimeout(pollTimer);pollTimer=setTimeout(refresh,250)}
async function action(fn){try{await fn();await refresh()}catch(e){q('error').className='error on';q('error').textContent=e.message}}
const setRoute=r=>action(()=>api('/api/route/'+r,'POST'));const startScene=()=>action(()=>api('/api/start','POST'));const autoDemo=()=>action(()=>api('/api/auto','POST'));const resetDemo=()=>action(()=>api('/api/reset','POST'));const setMode=m=>action(()=>api('/api/mode/'+m,'POST'));const newPattern=()=>action(()=>api('/api/pattern/new','POST'));const setPattern=()=>action(()=>fetch('/api/pattern',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seed:q('fixedPattern').value})}).then(async r=>{if(!r.ok)throw Error(await r.text());return r.json()}));barcode(null);refresh();
</script></body></html>"""
